### ISSUE TITLE
Test Plan for Part 2

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/openwrt-buildsystem-wrapper#25]
This is a Subtask for Migration to Major Release Part 2 Ticket #24 

# **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
- This scope is working with the new OpenWRT release so it has a major impact on all 3 value tracks
        1. Development
        2. Deployment
        3. Production
           
###  2. Create a short statement explaining the objectives and goals for this ticket.

- Test the new firmware so it can be approved for release, and debug as needed.
     
# **List of Subtasks:**

Repeat Part 1 Test Procedure on Part 2 firmware:
- [ ] Part 1: Subtask 1: Test for successful boot process 
- [ ] Part 1: Subtask 2:  Test WiFi AP, WiFi STA
- [ ] Part 1: Subtask 3: Test Ethernet networking
- [ ] Part 1: Subtask 4: Test USB and SD Card functionality
- [ ] Part 1: Subtask 5: Test I2C
- [ ] Part 1: Subtask 6: Test GPIO 

Test Part 2 Customized functionality:
- [ ] Part 2: Subtask 7: Test Pin multiplexing
- [ ] Part 2: Subtask 8: Test Hardware PWM
- [ ] Part 2: Subtask 8: Test NodeJS V18
- [ ] Part 2: Subtask 10: Test Device Tree overlay functioning 
  - [ ] Software SPI bus created
  - [ ] One wire Bus master created

# **Reference Material:**
###  1. Provide hyperlinks for helpful and related information. 
- OnionIoT/openwrt-buildsystem-wrapper

# **Deliverables or Desired Outcome:**

* Create a test plan to test new functionality listed in **List of Subtasks** section
* Create repeatable, mostly automated way to carry out these tests. See [comment below](https://github.com/OnionIoT/openwrt-buildsystem-wrapper/issues/25#issuecomment-2067357191)
* Screenshots/command line output demonstrating all Part 1 tests passing
* Screenshots/command line output demonstrating all Part 2 tests passing

# **Date Required By:**
###  1. When is the scope required to be completed?
- no specified completion date 

###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- Ticket #24    requires these test results to be completed.

**Comment by greenbreakfast** [comment]
Would like to have an automated and repeatable way for test firmware functionality.
Something along the lines of https://github.com/OnionIoT/omega2-fw-tester - note this is a proof of concept, open to suggestions and other solutions

**Comment by greenbreakfast** [comment]
Tested firmware released in #24 with the https://github.com/OnionIoT/omega2-fw-tester

| See release here: https://github.com/OnionIoT/OpenWRT-Packages/releases/tag/23.05.3-20240607
| Firmware available at: http://repo.onioniot.com.s3.amazonaws.com/omega2/images/openwrt-23.05/onion_omega2p-23.05.3-20240607.bin

Not all tests are passing, but I think it's a testing issue
<img width="1051" alt="Screenshot 2024-06-07 at 8 50 03 PM" src="https://github.com/OnionIoT/openwrt-buildsystem-wrapper/assets/6757320/779c7c0f-f1c6-499c-aca0-08f71d741444">

Full results: [results-20240607.txt](https://github.com/user-attachments/files/15746208/results-20240607.txt)

---


@YevheniiOnishchenkoLemberg let's make the following adjustments to the omega2-fw-tester:
* Please update the test numbering so the basic tests (boot, wifi, ethernet, usb, sd card, i2c, gpio) run first
* In the interest of reducing overall test time, let's run opkg update as a separate test just once before we do any other tests that need to do opkg install
* Let's run the dt overlay and one wire test last - see the detailed results above, the node test doesn't get valid output because the one-wire test is putting out a lot of messages
* Let's update the node test to be more evergreen - we can still run `node -v` but let's instead check for a 0 exit code instead of the actual version number

**Comment by greenbreakfast** [comment]
Merged the PR to the omega2-fw-tester and retested the firmware released in https://github.com/OnionIoT/openwrt-buildsystem-wrapper/issues/24

All tests passing!
<img width="1052" alt="image" src="https://github.com/OnionIoT/openwrt-buildsystem-wrapper/assets/6757320/ca49d257-7bc1-41e2-8031-00cd11d17b69">

---

@YevheniiOnishchenkoLemberg I appreciate the initiative on adding loops to the tests. But I think there's value in learning a test fails on the first try. It also keeps the overall test run shorter.
Could you please change it back to take out the loops?

**Comment by greenbreakfast** [comment]
Thanks for the fw-tester update @YevheniiOnishchenkoLemberg 


Running without the node tests on the same firmware as above:
![Image](https://github.com/OnionIoT/openwrt-buildsystem-wrapper/assets/6757320/f0fb2a2d-0c8c-4eb4-9ddc-badc725a40b4)

And running all tests:
![Image](https://github.com/OnionIoT/openwrt-buildsystem-wrapper/assets/6757320/66f218da-f53f-4e6e-8bb1-4d070c6e1b07)

-> Can save 6min by not running the node tests

Closing this issue since all tests are passing and the fw-tester updates are complete!
